"""empty message

Revision ID: d4b8b7f2c674
Revises: 5d458f9eba93
Create Date: 2024-08-27 19:38:59.325195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b8b7f2c674'
down_revision = '5d458f9eba93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siteusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siteusers', schema=None) as batch_op:
        batch_op.drop_column('investment')

    # ### end Alembic commands ###
